spring.datasource.url=jdbc:mysql://localhost:3306/cropcare
spring.datasource.username=root
spring.datasource.password=student
openrouter.api.key=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

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect